services:
  - type: web
    name: mindtube-backend
    env: node
    rootDir: server
    buildCommand: npm install && node -e "require('ytdlp-nodejs')"
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
